# version: '3'

# services:
#   mongodb:
#     image: mongo:5
#     restart: always
#     ports:
#       - 27020:27017
#     environment:
#       - MONGODB_DATABASE=nest-pokemon
#     volumes:
#       - ./mongo:/data/mongodb
version: '3'

services:
  mongodb:
    image: mongo:5
    restart: always
    ports:
      - 27020:27017
    environment:
      MONGODB_DATABASE: nest-pokemon
    volumes:
      - ./mongo:/data/mongodb